#!/bin/bash

pip install https://s3.amazonaws.com/connected-devices/Cython-0.27.3-cp27-cp27mu-linux_armv7l.whl || true
pip install https://s3.amazonaws.com/connected-devices/Kivy-1.10.1.dev0-cp27-cp27mu-linux_armv7l.whl || true
pip install paho-mqtt || true
